# Generated by Django 4.1.5 on 2023-01-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('behavior', models.IntegerField(choices=[(0, 'جيد'), (1, 'محايد'), (2, 'سيء')], default=0)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1', models.PositiveSmallIntegerField(blank=True, verbose_name='اللغة الانجليزية')),
                ('grade2', models.PositiveSmallIntegerField(blank=True, verbose_name='الحاسب')),
                ('grade3', models.PositiveSmallIntegerField(blank=True, verbose_name='رياضيات')),
                ('grade4', models.PositiveSmallIntegerField(blank=True, verbose_name='فيزياء')),
                ('grade5', models.PositiveSmallIntegerField(blank=True, verbose_name='كيمياء')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('students', models.ManyToManyField(to='main.student')),
            ],
        ),
    ]
